// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1193205938;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__mixer__analyze_waveforms_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_waveforms",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_buckets = <usize>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::mixer::analyze_waveforms(api_path, api_buckets)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__mixer__load_recording_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_recording",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_session_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::mixer::load_recording(api_path, api_session_path)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__mixer__player_seek_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_seek",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_frame = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::mixer::player_seek(api_frame);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__mixer__player_start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_tracks = <Vec<crate::api::mixer::ApiTrack>>::sse_decode(&mut deserializer);
            let api_master = <crate::api::mixer::ApiMaster>::sse_decode(&mut deserializer);
            let api_start_frame = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::mixer::player_start(
                            api_path,
                            api_tracks,
                            api_master,
                            api_start_frame,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__mixer__player_state_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_state",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::mixer::player_state())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__mixer__player_stop_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_stop",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::mixer::player_stop();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__mixer__player_update_params_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_update_params",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tracks = <Vec<crate::api::mixer::ApiTrack>>::sse_decode(&mut deserializer);
            let api_master = <crate::api::mixer::ApiMaster>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::mixer::player_update_params(api_tracks, api_master);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__mixer__render_mix_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "render_mix",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_wav_path = <String>::sse_decode(&mut deserializer);
            let api_out_path = <String>::sse_decode(&mut deserializer);
            let api_tracks = <Vec<crate::api::mixer::ApiTrack>>::sse_decode(&mut deserializer);
            let api_master = <crate::api::mixer::ApiMaster>::sse_decode(&mut deserializer);
            let api_events = <StreamSink<
                crate::api::mixer::RenderEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::mixer::render_mix(
                            api_wav_path,
                            api_out_path,
                            api_tracks,
                            api_master,
                            api_events,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__mixer__save_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "save_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_path = <String>::sse_decode(&mut deserializer);
            let api_tracks = <Vec<crate::api::mixer::ApiTrack>>::sse_decode(&mut deserializer);
            let api_master = <crate::api::mixer::ApiMaster>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::mixer::save_session(
                            api_session_path,
                            api_tracks,
                            api_master,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::mixer::RenderEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::mixer::ApiChannelWaveform {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_min = <Vec<f32>>::sse_decode(deserializer);
        let mut var_max = <Vec<f32>>::sse_decode(deserializer);
        let mut var_peakDbfs = <f32>::sse_decode(deserializer);
        return crate::api::mixer::ApiChannelWaveform {
            min: var_min,
            max: var_max,
            peak_dbfs: var_peakDbfs,
        };
    }
}

impl SseDecode for crate::api::mixer::ApiEqBand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_enabled = <bool>::sse_decode(deserializer);
        let mut var_freq = <f64>::sse_decode(deserializer);
        let mut var_gainDb = <f64>::sse_decode(deserializer);
        let mut var_q = <f64>::sse_decode(deserializer);
        return crate::api::mixer::ApiEqBand {
            enabled: var_enabled,
            freq: var_freq,
            gain_db: var_gainDb,
            q: var_q,
        };
    }
}

impl SseDecode for crate::api::mixer::ApiFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::mixer::ApiFormat::Wav16,
            1 => crate::api::mixer::ApiFormat::Wav24,
            2 => crate::api::mixer::ApiFormat::Wav32Float,
            _ => unreachable!("Invalid variant for ApiFormat: {}", inner),
        };
    }
}

impl SseDecode for crate::api::mixer::ApiHpfSlope {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::mixer::ApiHpfSlope::Db12,
            1 => crate::api::mixer::ApiHpfSlope::Db24,
            _ => unreachable!("Invalid variant for ApiHpfSlope: {}", inner),
        };
    }
}

impl SseDecode for crate::api::mixer::ApiLoudness {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_mode = <crate::api::mixer::ApiLoudnessMode>::sse_decode(deserializer);
        let mut var_value = <f64>::sse_decode(deserializer);
        return crate::api::mixer::ApiLoudness {
            mode: var_mode,
            value: var_value,
        };
    }
}

impl SseDecode for crate::api::mixer::ApiLoudnessMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::mixer::ApiLoudnessMode::None,
            1 => crate::api::mixer::ApiLoudnessMode::PeakDbfs,
            2 => crate::api::mixer::ApiLoudnessMode::LufsIntegrated,
            _ => unreachable!("Invalid variant for ApiLoudnessMode: {}", inner),
        };
    }
}

impl SseDecode for crate::api::mixer::ApiMaster {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_loudness = <crate::api::mixer::ApiLoudness>::sse_decode(deserializer);
        let mut var_format = <crate::api::mixer::ApiFormat>::sse_decode(deserializer);
        let mut var_limiterEnabled = <bool>::sse_decode(deserializer);
        let mut var_ceilingDbtp = <f64>::sse_decode(deserializer);
        let mut var_dither = <bool>::sse_decode(deserializer);
        return crate::api::mixer::ApiMaster {
            loudness: var_loudness,
            format: var_format,
            limiter_enabled: var_limiterEnabled,
            ceiling_dbtp: var_ceilingDbtp,
            dither: var_dither,
        };
    }
}

impl SseDecode for crate::api::mixer::ApiPlayerState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_playing = <bool>::sse_decode(deserializer);
        let mut var_positionFrames = <u64>::sse_decode(deserializer);
        let mut var_peakL = <f32>::sse_decode(deserializer);
        let mut var_peakR = <f32>::sse_decode(deserializer);
        let mut var_lufsMomentary = <f32>::sse_decode(deserializer);
        let mut var_lufsIntegrated = <f32>::sse_decode(deserializer);
        let mut var_truePeak = <f32>::sse_decode(deserializer);
        let mut var_correlation = <f32>::sse_decode(deserializer);
        return crate::api::mixer::ApiPlayerState {
            playing: var_playing,
            position_frames: var_positionFrames,
            peak_l: var_peakL,
            peak_r: var_peakR,
            lufs_momentary: var_lufsMomentary,
            lufs_integrated: var_lufsIntegrated,
            true_peak: var_truePeak,
            correlation: var_correlation,
        };
    }
}

impl SseDecode for crate::api::mixer::ApiRenderReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_peakDbfsBefore = <f64>::sse_decode(deserializer);
        let mut var_gainAppliedDb = <f64>::sse_decode(deserializer);
        let mut var_durationSeconds = <f64>::sse_decode(deserializer);
        let mut var_sampleRate = <u32>::sse_decode(deserializer);
        let mut var_integratedLufs = <f64>::sse_decode(deserializer);
        let mut var_truePeakDbtp = <f64>::sse_decode(deserializer);
        let mut var_lraLu = <f64>::sse_decode(deserializer);
        let mut var_sourceIntegratedLufs = <f64>::sse_decode(deserializer);
        return crate::api::mixer::ApiRenderReport {
            peak_dbfs_before: var_peakDbfsBefore,
            gain_applied_db: var_gainAppliedDb,
            duration_seconds: var_durationSeconds,
            sample_rate: var_sampleRate,
            integrated_lufs: var_integratedLufs,
            true_peak_dbtp: var_truePeakDbtp,
            lra_lu: var_lraLu,
            source_integrated_lufs: var_sourceIntegratedLufs,
        };
    }
}

impl SseDecode for crate::api::mixer::ApiTrack {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_index = <u32>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_gainDb = <f64>::sse_decode(deserializer);
        let mut var_pan = <f64>::sse_decode(deserializer);
        let mut var_polarityInvert = <bool>::sse_decode(deserializer);
        let mut var_muted = <bool>::sse_decode(deserializer);
        let mut var_solo = <bool>::sse_decode(deserializer);
        let mut var_inMix = <bool>::sse_decode(deserializer);
        let mut var_eq = <crate::api::mixer::ApiTrackEq>::sse_decode(deserializer);
        return crate::api::mixer::ApiTrack {
            index: var_index,
            name: var_name,
            gain_db: var_gainDb,
            pan: var_pan,
            polarity_invert: var_polarityInvert,
            muted: var_muted,
            solo: var_solo,
            in_mix: var_inMix,
            eq: var_eq,
        };
    }
}

impl SseDecode for crate::api::mixer::ApiTrackEq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_hpfEnabled = <bool>::sse_decode(deserializer);
        let mut var_hpfFreq = <f64>::sse_decode(deserializer);
        let mut var_hpfSlope = <crate::api::mixer::ApiHpfSlope>::sse_decode(deserializer);
        let mut var_low = <crate::api::mixer::ApiEqBand>::sse_decode(deserializer);
        let mut var_mid = <crate::api::mixer::ApiEqBand>::sse_decode(deserializer);
        let mut var_high = <crate::api::mixer::ApiEqBand>::sse_decode(deserializer);
        return crate::api::mixer::ApiTrackEq {
            hpf_enabled: var_hpfEnabled,
            hpf_freq: var_hpfFreq,
            hpf_slope: var_hpfSlope,
            low: var_low,
            mid: var_mid,
            high: var_high,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::mixer::ApiChannelWaveform> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::mixer::ApiChannelWaveform>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::mixer::ApiTrack> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::mixer::ApiTrack>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::api::mixer::ApiRenderReport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::mixer::ApiRenderReport>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::mixer::RecordingInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_sampleRate = <u32>::sse_decode(deserializer);
        let mut var_channels = <u16>::sse_decode(deserializer);
        let mut var_bitsPerSample = <u16>::sse_decode(deserializer);
        let mut var_numFrames = <u64>::sse_decode(deserializer);
        let mut var_durationSeconds = <f64>::sse_decode(deserializer);
        let mut var_tracks = <Vec<crate::api::mixer::ApiTrack>>::sse_decode(deserializer);
        let mut var_master = <crate::api::mixer::ApiMaster>::sse_decode(deserializer);
        return crate::api::mixer::RecordingInfo {
            path: var_path,
            sample_rate: var_sampleRate,
            channels: var_channels,
            bits_per_sample: var_bitsPerSample,
            num_frames: var_numFrames,
            duration_seconds: var_durationSeconds,
            tracks: var_tracks,
            master: var_master,
        };
    }
}

impl SseDecode for crate::api::mixer::RenderEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_progress = <f32>::sse_decode(deserializer);
        let mut var_report = <Option<crate::api::mixer::ApiRenderReport>>::sse_decode(deserializer);
        return crate::api::mixer::RenderEvent {
            progress: var_progress,
            report: var_report,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__mixer__analyze_waveforms_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__mixer__load_recording_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__mixer__player_seek_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__mixer__player_start_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__mixer__player_stop_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__mixer__player_update_params_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__mixer__render_mix_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__mixer__save_session_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__mixer__player_state_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiChannelWaveform {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.min.into_into_dart().into_dart(),
            self.max.into_into_dart().into_dart(),
            self.peak_dbfs.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mixer::ApiChannelWaveform
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiChannelWaveform>
    for crate::api::mixer::ApiChannelWaveform
{
    fn into_into_dart(self) -> crate::api::mixer::ApiChannelWaveform {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiEqBand {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.enabled.into_into_dart().into_dart(),
            self.freq.into_into_dart().into_dart(),
            self.gain_db.into_into_dart().into_dart(),
            self.q.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::mixer::ApiEqBand {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiEqBand>
    for crate::api::mixer::ApiEqBand
{
    fn into_into_dart(self) -> crate::api::mixer::ApiEqBand {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Wav16 => 0.into_dart(),
            Self::Wav24 => 1.into_dart(),
            Self::Wav32Float => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::mixer::ApiFormat {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiFormat>
    for crate::api::mixer::ApiFormat
{
    fn into_into_dart(self) -> crate::api::mixer::ApiFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiHpfSlope {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Db12 => 0.into_dart(),
            Self::Db24 => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mixer::ApiHpfSlope
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiHpfSlope>
    for crate::api::mixer::ApiHpfSlope
{
    fn into_into_dart(self) -> crate::api::mixer::ApiHpfSlope {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiLoudness {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.mode.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mixer::ApiLoudness
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiLoudness>
    for crate::api::mixer::ApiLoudness
{
    fn into_into_dart(self) -> crate::api::mixer::ApiLoudness {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiLoudnessMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::None => 0.into_dart(),
            Self::PeakDbfs => 1.into_dart(),
            Self::LufsIntegrated => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mixer::ApiLoudnessMode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiLoudnessMode>
    for crate::api::mixer::ApiLoudnessMode
{
    fn into_into_dart(self) -> crate::api::mixer::ApiLoudnessMode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiMaster {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.loudness.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.limiter_enabled.into_into_dart().into_dart(),
            self.ceiling_dbtp.into_into_dart().into_dart(),
            self.dither.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::mixer::ApiMaster {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiMaster>
    for crate::api::mixer::ApiMaster
{
    fn into_into_dart(self) -> crate::api::mixer::ApiMaster {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiPlayerState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.playing.into_into_dart().into_dart(),
            self.position_frames.into_into_dart().into_dart(),
            self.peak_l.into_into_dart().into_dart(),
            self.peak_r.into_into_dart().into_dart(),
            self.lufs_momentary.into_into_dart().into_dart(),
            self.lufs_integrated.into_into_dart().into_dart(),
            self.true_peak.into_into_dart().into_dart(),
            self.correlation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mixer::ApiPlayerState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiPlayerState>
    for crate::api::mixer::ApiPlayerState
{
    fn into_into_dart(self) -> crate::api::mixer::ApiPlayerState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiRenderReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.peak_dbfs_before.into_into_dart().into_dart(),
            self.gain_applied_db.into_into_dart().into_dart(),
            self.duration_seconds.into_into_dart().into_dart(),
            self.sample_rate.into_into_dart().into_dart(),
            self.integrated_lufs.into_into_dart().into_dart(),
            self.true_peak_dbtp.into_into_dart().into_dart(),
            self.lra_lu.into_into_dart().into_dart(),
            self.source_integrated_lufs.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mixer::ApiRenderReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiRenderReport>
    for crate::api::mixer::ApiRenderReport
{
    fn into_into_dart(self) -> crate::api::mixer::ApiRenderReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiTrack {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.index.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.gain_db.into_into_dart().into_dart(),
            self.pan.into_into_dart().into_dart(),
            self.polarity_invert.into_into_dart().into_dart(),
            self.muted.into_into_dart().into_dart(),
            self.solo.into_into_dart().into_dart(),
            self.in_mix.into_into_dart().into_dart(),
            self.eq.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::mixer::ApiTrack {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiTrack>
    for crate::api::mixer::ApiTrack
{
    fn into_into_dart(self) -> crate::api::mixer::ApiTrack {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::ApiTrackEq {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.hpf_enabled.into_into_dart().into_dart(),
            self.hpf_freq.into_into_dart().into_dart(),
            self.hpf_slope.into_into_dart().into_dart(),
            self.low.into_into_dart().into_dart(),
            self.mid.into_into_dart().into_dart(),
            self.high.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::mixer::ApiTrackEq {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::ApiTrackEq>
    for crate::api::mixer::ApiTrackEq
{
    fn into_into_dart(self) -> crate::api::mixer::ApiTrackEq {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::RecordingInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.sample_rate.into_into_dart().into_dart(),
            self.channels.into_into_dart().into_dart(),
            self.bits_per_sample.into_into_dart().into_dart(),
            self.num_frames.into_into_dart().into_dart(),
            self.duration_seconds.into_into_dart().into_dart(),
            self.tracks.into_into_dart().into_dart(),
            self.master.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mixer::RecordingInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::RecordingInfo>
    for crate::api::mixer::RecordingInfo
{
    fn into_into_dart(self) -> crate::api::mixer::RecordingInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::mixer::RenderEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.progress.into_into_dart().into_dart(),
            self.report.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::mixer::RenderEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::mixer::RenderEvent>
    for crate::api::mixer::RenderEvent
{
    fn into_into_dart(self) -> crate::api::mixer::RenderEvent {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::mixer::RenderEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::mixer::ApiChannelWaveform {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<f32>>::sse_encode(self.min, serializer);
        <Vec<f32>>::sse_encode(self.max, serializer);
        <f32>::sse_encode(self.peak_dbfs, serializer);
    }
}

impl SseEncode for crate::api::mixer::ApiEqBand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.enabled, serializer);
        <f64>::sse_encode(self.freq, serializer);
        <f64>::sse_encode(self.gain_db, serializer);
        <f64>::sse_encode(self.q, serializer);
    }
}

impl SseEncode for crate::api::mixer::ApiFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::mixer::ApiFormat::Wav16 => 0,
                crate::api::mixer::ApiFormat::Wav24 => 1,
                crate::api::mixer::ApiFormat::Wav32Float => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::mixer::ApiHpfSlope {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::mixer::ApiHpfSlope::Db12 => 0,
                crate::api::mixer::ApiHpfSlope::Db24 => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::mixer::ApiLoudness {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::mixer::ApiLoudnessMode>::sse_encode(self.mode, serializer);
        <f64>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::api::mixer::ApiLoudnessMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::mixer::ApiLoudnessMode::None => 0,
                crate::api::mixer::ApiLoudnessMode::PeakDbfs => 1,
                crate::api::mixer::ApiLoudnessMode::LufsIntegrated => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::mixer::ApiMaster {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::mixer::ApiLoudness>::sse_encode(self.loudness, serializer);
        <crate::api::mixer::ApiFormat>::sse_encode(self.format, serializer);
        <bool>::sse_encode(self.limiter_enabled, serializer);
        <f64>::sse_encode(self.ceiling_dbtp, serializer);
        <bool>::sse_encode(self.dither, serializer);
    }
}

impl SseEncode for crate::api::mixer::ApiPlayerState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.playing, serializer);
        <u64>::sse_encode(self.position_frames, serializer);
        <f32>::sse_encode(self.peak_l, serializer);
        <f32>::sse_encode(self.peak_r, serializer);
        <f32>::sse_encode(self.lufs_momentary, serializer);
        <f32>::sse_encode(self.lufs_integrated, serializer);
        <f32>::sse_encode(self.true_peak, serializer);
        <f32>::sse_encode(self.correlation, serializer);
    }
}

impl SseEncode for crate::api::mixer::ApiRenderReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.peak_dbfs_before, serializer);
        <f64>::sse_encode(self.gain_applied_db, serializer);
        <f64>::sse_encode(self.duration_seconds, serializer);
        <u32>::sse_encode(self.sample_rate, serializer);
        <f64>::sse_encode(self.integrated_lufs, serializer);
        <f64>::sse_encode(self.true_peak_dbtp, serializer);
        <f64>::sse_encode(self.lra_lu, serializer);
        <f64>::sse_encode(self.source_integrated_lufs, serializer);
    }
}

impl SseEncode for crate::api::mixer::ApiTrack {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.index, serializer);
        <String>::sse_encode(self.name, serializer);
        <f64>::sse_encode(self.gain_db, serializer);
        <f64>::sse_encode(self.pan, serializer);
        <bool>::sse_encode(self.polarity_invert, serializer);
        <bool>::sse_encode(self.muted, serializer);
        <bool>::sse_encode(self.solo, serializer);
        <bool>::sse_encode(self.in_mix, serializer);
        <crate::api::mixer::ApiTrackEq>::sse_encode(self.eq, serializer);
    }
}

impl SseEncode for crate::api::mixer::ApiTrackEq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.hpf_enabled, serializer);
        <f64>::sse_encode(self.hpf_freq, serializer);
        <crate::api::mixer::ApiHpfSlope>::sse_encode(self.hpf_slope, serializer);
        <crate::api::mixer::ApiEqBand>::sse_encode(self.low, serializer);
        <crate::api::mixer::ApiEqBand>::sse_encode(self.mid, serializer);
        <crate::api::mixer::ApiEqBand>::sse_encode(self.high, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::mixer::ApiChannelWaveform> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::mixer::ApiChannelWaveform>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::mixer::ApiTrack> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::mixer::ApiTrack>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::mixer::ApiRenderReport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::mixer::ApiRenderReport>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::mixer::RecordingInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <u32>::sse_encode(self.sample_rate, serializer);
        <u16>::sse_encode(self.channels, serializer);
        <u16>::sse_encode(self.bits_per_sample, serializer);
        <u64>::sse_encode(self.num_frames, serializer);
        <f64>::sse_encode(self.duration_seconds, serializer);
        <Vec<crate::api::mixer::ApiTrack>>::sse_encode(self.tracks, serializer);
        <crate::api::mixer::ApiMaster>::sse_encode(self.master, serializer);
    }
}

impl SseEncode for crate::api::mixer::RenderEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.progress, serializer);
        <Option<crate::api::mixer::ApiRenderReport>>::sse_encode(self.report, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
