// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/mixer.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<RenderEvent> dco_decode_StreamSink_render_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApiAnalysis dco_decode_api_analysis(dynamic raw);

  @protected
  ApiChannelWaveform dco_decode_api_channel_waveform(dynamic raw);

  @protected
  ApiEqBand dco_decode_api_eq_band(dynamic raw);

  @protected
  ApiFormat dco_decode_api_format(dynamic raw);

  @protected
  ApiHpfSlope dco_decode_api_hpf_slope(dynamic raw);

  @protected
  ApiLoudness dco_decode_api_loudness(dynamic raw);

  @protected
  ApiLoudnessMode dco_decode_api_loudness_mode(dynamic raw);

  @protected
  ApiMaster dco_decode_api_master(dynamic raw);

  @protected
  ApiPlayerState dco_decode_api_player_state(dynamic raw);

  @protected
  ApiRenderReport dco_decode_api_render_report(dynamic raw);

  @protected
  ApiTrack dco_decode_api_track(dynamic raw);

  @protected
  ApiTrackEq dco_decode_api_track_eq(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApiMaster dco_decode_box_autoadd_api_master(dynamic raw);

  @protected
  ApiRenderReport dco_decode_box_autoadd_api_render_report(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ApiChannelWaveform> dco_decode_list_api_channel_waveform(dynamic raw);

  @protected
  List<ApiTrack> dco_decode_list_api_track(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  ApiRenderReport? dco_decode_opt_box_autoadd_api_render_report(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  RecordingInfo dco_decode_recording_info(dynamic raw);

  @protected
  RenderEvent dco_decode_render_event(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<RenderEvent> sse_decode_StreamSink_render_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiAnalysis sse_decode_api_analysis(SseDeserializer deserializer);

  @protected
  ApiChannelWaveform sse_decode_api_channel_waveform(
    SseDeserializer deserializer,
  );

  @protected
  ApiEqBand sse_decode_api_eq_band(SseDeserializer deserializer);

  @protected
  ApiFormat sse_decode_api_format(SseDeserializer deserializer);

  @protected
  ApiHpfSlope sse_decode_api_hpf_slope(SseDeserializer deserializer);

  @protected
  ApiLoudness sse_decode_api_loudness(SseDeserializer deserializer);

  @protected
  ApiLoudnessMode sse_decode_api_loudness_mode(SseDeserializer deserializer);

  @protected
  ApiMaster sse_decode_api_master(SseDeserializer deserializer);

  @protected
  ApiPlayerState sse_decode_api_player_state(SseDeserializer deserializer);

  @protected
  ApiRenderReport sse_decode_api_render_report(SseDeserializer deserializer);

  @protected
  ApiTrack sse_decode_api_track(SseDeserializer deserializer);

  @protected
  ApiTrackEq sse_decode_api_track_eq(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApiMaster sse_decode_box_autoadd_api_master(SseDeserializer deserializer);

  @protected
  ApiRenderReport sse_decode_box_autoadd_api_render_report(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ApiChannelWaveform> sse_decode_list_api_channel_waveform(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiTrack> sse_decode_list_api_track(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ApiRenderReport? sse_decode_opt_box_autoadd_api_render_report(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  RecordingInfo sse_decode_recording_info(SseDeserializer deserializer);

  @protected
  RenderEvent sse_decode_render_event(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_render_event_Sse(
    RustStreamSink<RenderEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_analysis(ApiAnalysis self, SseSerializer serializer);

  @protected
  void sse_encode_api_channel_waveform(
    ApiChannelWaveform self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_eq_band(ApiEqBand self, SseSerializer serializer);

  @protected
  void sse_encode_api_format(ApiFormat self, SseSerializer serializer);

  @protected
  void sse_encode_api_hpf_slope(ApiHpfSlope self, SseSerializer serializer);

  @protected
  void sse_encode_api_loudness(ApiLoudness self, SseSerializer serializer);

  @protected
  void sse_encode_api_loudness_mode(
    ApiLoudnessMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_master(ApiMaster self, SseSerializer serializer);

  @protected
  void sse_encode_api_player_state(
    ApiPlayerState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_render_report(
    ApiRenderReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_track(ApiTrack self, SseSerializer serializer);

  @protected
  void sse_encode_api_track_eq(ApiTrackEq self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_master(
    ApiMaster self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_render_report(
    ApiRenderReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_channel_waveform(
    List<ApiChannelWaveform> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_track(List<ApiTrack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_render_report(
    ApiRenderReport? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_recording_info(RecordingInfo self, SseSerializer serializer);

  @protected
  void sse_encode_render_event(RenderEvent self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
