// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mixer.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -865305758;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_durecmix',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<MixStatsEvent> crateApiMixerAnalyzeMixMastering({
    required String path,
    required List<ApiTrack> tracks,
    required ApiMaster master,
    int? fd,
  });

  Future<ApiAnalysis> crateApiMixerAnalyzeRecording({
    required String path,
    required BigInt buckets,
    int? fd,
  });

  Stream<ReferenceEvent> crateApiMixerAnalyzeReference({
    required String path,
    int? fd,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<RecordingInfo> crateApiMixerLoadRecording({
    required String path,
    required String sessionPath,
    int? fd,
  });

  Future<ApiReferenceProfile> crateApiMixerMergeReferenceProfiles({
    required List<ApiReferenceProfile> profiles,
  });

  Future<void> crateApiMixerPlayerSeek({required BigInt frame});

  Future<void> crateApiMixerPlayerStart({
    required String path,
    required List<ApiTrack> tracks,
    required ApiMaster master,
    required BigInt startFrame,
    int? fd,
    ApiMixStats? masteringStats,
    ApiReferenceProfile? reference,
  });

  ApiPlayerState crateApiMixerPlayerState();

  Future<void> crateApiMixerPlayerStop();

  Future<void> crateApiMixerPlayerUpdateParams({
    required List<ApiTrack> tracks,
    required ApiMaster master,
    ApiMixStats? masteringStats,
    ApiReferenceProfile? reference,
  });

  Future<ApiProbe> crateApiMixerProbeRecording({required String path, int? fd});

  Future<int> crateApiMixerReferenceProfileVersion();

  Stream<RenderEvent> crateApiMixerRenderMix({
    required String wavPath,
    required String outPath,
    required List<ApiTrack> tracks,
    required ApiMaster master,
    ApiReferenceProfile? reference,
    int? inputFd,
    int? outputFd,
  });

  Future<void> crateApiMixerSaveSession({
    required String sessionPath,
    required List<ApiTrack> tracks,
    required ApiMaster master,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<MixStatsEvent> crateApiMixerAnalyzeMixMastering({
    required String path,
    required List<ApiTrack> tracks,
    required ApiMaster master,
    int? fd,
  }) {
    final events = RustStreamSink<MixStatsEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(path, serializer);
            sse_encode_list_api_track(tracks, serializer);
            sse_encode_box_autoadd_api_master(master, serializer);
            sse_encode_opt_box_autoadd_i_32(fd, serializer);
            sse_encode_StreamSink_mix_stats_event_Sse(events, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiMixerAnalyzeMixMasteringConstMeta,
          argValues: [path, tracks, master, fd, events],
          apiImpl: this,
        ),
      ),
    );
    return events.stream;
  }

  TaskConstMeta get kCrateApiMixerAnalyzeMixMasteringConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_mix_mastering",
        argNames: ["path", "tracks", "master", "fd", "events"],
      );

  @override
  Future<ApiAnalysis> crateApiMixerAnalyzeRecording({
    required String path,
    required BigInt buckets,
    int? fd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_usize(buckets, serializer);
          sse_encode_opt_box_autoadd_i_32(fd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_analysis,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMixerAnalyzeRecordingConstMeta,
        argValues: [path, buckets, fd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerAnalyzeRecordingConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_recording",
        argNames: ["path", "buckets", "fd"],
      );

  @override
  Stream<ReferenceEvent> crateApiMixerAnalyzeReference({
    required String path,
    int? fd,
  }) {
    final events = RustStreamSink<ReferenceEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(path, serializer);
            sse_encode_opt_box_autoadd_i_32(fd, serializer);
            sse_encode_StreamSink_reference_event_Sse(events, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiMixerAnalyzeReferenceConstMeta,
          argValues: [path, fd, events],
          apiImpl: this,
        ),
      ),
    );
    return events.stream;
  }

  TaskConstMeta get kCrateApiMixerAnalyzeReferenceConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_reference",
        argNames: ["path", "fd", "events"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<RecordingInfo> crateApiMixerLoadRecording({
    required String path,
    required String sessionPath,
    int? fd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(sessionPath, serializer);
          sse_encode_opt_box_autoadd_i_32(fd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recording_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMixerLoadRecordingConstMeta,
        argValues: [path, sessionPath, fd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerLoadRecordingConstMeta => const TaskConstMeta(
    debugName: "load_recording",
    argNames: ["path", "sessionPath", "fd"],
  );

  @override
  Future<ApiReferenceProfile> crateApiMixerMergeReferenceProfiles({
    required List<ApiReferenceProfile> profiles,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_api_reference_profile(profiles, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_reference_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMixerMergeReferenceProfilesConstMeta,
        argValues: [profiles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerMergeReferenceProfilesConstMeta =>
      const TaskConstMeta(
        debugName: "merge_reference_profiles",
        argNames: ["profiles"],
      );

  @override
  Future<void> crateApiMixerPlayerSeek({required BigInt frame}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(frame, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMixerPlayerSeekConstMeta,
        argValues: [frame],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerPlayerSeekConstMeta =>
      const TaskConstMeta(debugName: "player_seek", argNames: ["frame"]);

  @override
  Future<void> crateApiMixerPlayerStart({
    required String path,
    required List<ApiTrack> tracks,
    required ApiMaster master,
    required BigInt startFrame,
    int? fd,
    ApiMixStats? masteringStats,
    ApiReferenceProfile? reference,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_api_track(tracks, serializer);
          sse_encode_box_autoadd_api_master(master, serializer);
          sse_encode_u_64(startFrame, serializer);
          sse_encode_opt_box_autoadd_i_32(fd, serializer);
          sse_encode_opt_box_autoadd_api_mix_stats(masteringStats, serializer);
          sse_encode_opt_box_autoadd_api_reference_profile(
            reference,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMixerPlayerStartConstMeta,
        argValues: [
          path,
          tracks,
          master,
          startFrame,
          fd,
          masteringStats,
          reference,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerPlayerStartConstMeta => const TaskConstMeta(
    debugName: "player_start",
    argNames: [
      "path",
      "tracks",
      "master",
      "startFrame",
      "fd",
      "masteringStats",
      "reference",
    ],
  );

  @override
  ApiPlayerState crateApiMixerPlayerState() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_player_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMixerPlayerStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerPlayerStateConstMeta =>
      const TaskConstMeta(debugName: "player_state", argNames: []);

  @override
  Future<void> crateApiMixerPlayerStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMixerPlayerStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerPlayerStopConstMeta =>
      const TaskConstMeta(debugName: "player_stop", argNames: []);

  @override
  Future<void> crateApiMixerPlayerUpdateParams({
    required List<ApiTrack> tracks,
    required ApiMaster master,
    ApiMixStats? masteringStats,
    ApiReferenceProfile? reference,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_api_track(tracks, serializer);
          sse_encode_box_autoadd_api_master(master, serializer);
          sse_encode_opt_box_autoadd_api_mix_stats(masteringStats, serializer);
          sse_encode_opt_box_autoadd_api_reference_profile(
            reference,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMixerPlayerUpdateParamsConstMeta,
        argValues: [tracks, master, masteringStats, reference],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerPlayerUpdateParamsConstMeta =>
      const TaskConstMeta(
        debugName: "player_update_params",
        argNames: ["tracks", "master", "masteringStats", "reference"],
      );

  @override
  Future<ApiProbe> crateApiMixerProbeRecording({
    required String path,
    int? fd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_opt_box_autoadd_i_32(fd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_probe,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMixerProbeRecordingConstMeta,
        argValues: [path, fd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerProbeRecordingConstMeta =>
      const TaskConstMeta(
        debugName: "probe_recording",
        argNames: ["path", "fd"],
      );

  @override
  Future<int> crateApiMixerReferenceProfileVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMixerReferenceProfileVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerReferenceProfileVersionConstMeta =>
      const TaskConstMeta(debugName: "reference_profile_version", argNames: []);

  @override
  Stream<RenderEvent> crateApiMixerRenderMix({
    required String wavPath,
    required String outPath,
    required List<ApiTrack> tracks,
    required ApiMaster master,
    ApiReferenceProfile? reference,
    int? inputFd,
    int? outputFd,
  }) {
    final events = RustStreamSink<RenderEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(wavPath, serializer);
            sse_encode_String(outPath, serializer);
            sse_encode_list_api_track(tracks, serializer);
            sse_encode_box_autoadd_api_master(master, serializer);
            sse_encode_opt_box_autoadd_api_reference_profile(
              reference,
              serializer,
            );
            sse_encode_opt_box_autoadd_i_32(inputFd, serializer);
            sse_encode_opt_box_autoadd_i_32(outputFd, serializer);
            sse_encode_StreamSink_render_event_Sse(events, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiMixerRenderMixConstMeta,
          argValues: [
            wavPath,
            outPath,
            tracks,
            master,
            reference,
            inputFd,
            outputFd,
            events,
          ],
          apiImpl: this,
        ),
      ),
    );
    return events.stream;
  }

  TaskConstMeta get kCrateApiMixerRenderMixConstMeta => const TaskConstMeta(
    debugName: "render_mix",
    argNames: [
      "wavPath",
      "outPath",
      "tracks",
      "master",
      "reference",
      "inputFd",
      "outputFd",
      "events",
    ],
  );

  @override
  Future<void> crateApiMixerSaveSession({
    required String sessionPath,
    required List<ApiTrack> tracks,
    required ApiMaster master,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionPath, serializer);
          sse_encode_list_api_track(tracks, serializer);
          sse_encode_box_autoadd_api_master(master, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMixerSaveSessionConstMeta,
        argValues: [sessionPath, tracks, master],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMixerSaveSessionConstMeta => const TaskConstMeta(
    debugName: "save_session",
    argNames: ["sessionPath", "tracks", "master"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<MixStatsEvent> dco_decode_StreamSink_mix_stats_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ReferenceEvent> dco_decode_StreamSink_reference_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<RenderEvent> dco_decode_StreamSink_render_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiAnalysis dco_decode_api_analysis(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiAnalysis(
      waveforms: dco_decode_list_api_channel_waveform(arr[0]),
      bpm: dco_decode_opt_box_autoadd_f_64(arr[1]),
    );
  }

  @protected
  ApiChannelWaveform dco_decode_api_channel_waveform(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiChannelWaveform(
      min: dco_decode_list_prim_f_32_strict(arr[0]),
      max: dco_decode_list_prim_f_32_strict(arr[1]),
      peakDbfs: dco_decode_f_32(arr[2]),
    );
  }

  @protected
  ApiEqBand dco_decode_api_eq_band(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ApiEqBand(
      enabled: dco_decode_bool(arr[0]),
      freq: dco_decode_f_64(arr[1]),
      gainDb: dco_decode_f_64(arr[2]),
      q: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  ApiFormat dco_decode_api_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiFormat.values[raw as int];
  }

  @protected
  ApiHpfSlope dco_decode_api_hpf_slope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiHpfSlope.values[raw as int];
  }

  @protected
  ApiLoudness dco_decode_api_loudness(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiLoudness(
      mode: dco_decode_api_loudness_mode(arr[0]),
      value: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  ApiLoudnessMode dco_decode_api_loudness_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiLoudnessMode.values[raw as int];
  }

  @protected
  ApiMaster dco_decode_api_master(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ApiMaster(
      loudness: dco_decode_api_loudness(arr[0]),
      format: dco_decode_api_format(arr[1]),
      limiterEnabled: dco_decode_bool(arr[2]),
      ceilingDbtp: dco_decode_f_64(arr[3]),
      dither: dco_decode_bool(arr[4]),
      trimStartFrame: dco_decode_u_64(arr[5]),
      trimEndFrame: dco_decode_opt_box_autoadd_u_64(arr[6]),
      fadeInMs: dco_decode_f_64(arr[7]),
      fadeOutMs: dco_decode_f_64(arr[8]),
      masteringEnabled: dco_decode_bool(arr[9]),
      masteringReferences: dco_decode_list_api_mastering_reference(arr[10]),
    );
  }

  @protected
  ApiMasteringReference dco_decode_api_mastering_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiMasteringReference(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  ApiMixStats dco_decode_api_mix_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ApiMixStats(
      sampleRate: dco_decode_u_32(arr[0]),
      durationSeconds: dco_decode_f_64(arr[1]),
      midRms: dco_decode_f_64(arr[2]),
      sideRms: dco_decode_f_64(arr[3]),
      midSpectrum: dco_decode_list_prim_f_64_strict(arr[4]),
      sideSpectrum: dco_decode_list_prim_f_64_strict(arr[5]),
      midPower: dco_decode_list_prim_f_64_strict(arr[6]),
      sidePower: dco_decode_list_prim_f_64_strict(arr[7]),
    );
  }

  @protected
  ApiPlayerState dco_decode_api_player_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ApiPlayerState(
      playing: dco_decode_bool(arr[0]),
      positionFrames: dco_decode_u_64(arr[1]),
      peakL: dco_decode_f_32(arr[2]),
      peakR: dco_decode_f_32(arr[3]),
      lufsMomentary: dco_decode_f_32(arr[4]),
      lufsIntegrated: dco_decode_f_32(arr[5]),
      truePeak: dco_decode_f_32(arr[6]),
      correlation: dco_decode_f_32(arr[7]),
    );
  }

  @protected
  ApiProbe dco_decode_api_probe(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ApiProbe(
      channels: dco_decode_u_16(arr[0]),
      sampleRate: dco_decode_u_32(arr[1]),
      bitsPerSample: dco_decode_u_16(arr[2]),
      numFrames: dco_decode_u_64(arr[3]),
      durationSeconds: dco_decode_f_64(arr[4]),
      ixmlTrackCount: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  ApiReferenceProfile dco_decode_api_reference_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ApiReferenceProfile(
      version: dco_decode_u_32(arr[0]),
      sampleRate: dco_decode_u_32(arr[1]),
      fftSize: dco_decode_u_32(arr[2]),
      pieceSeconds: dco_decode_f_64(arr[3]),
      durationSeconds: dco_decode_f_64(arr[4]),
      midRms: dco_decode_f_64(arr[5]),
      sideRms: dco_decode_f_64(arr[6]),
      midSpectrum: dco_decode_list_prim_f_32_strict(arr[7]),
      sideSpectrum: dco_decode_list_prim_f_32_strict(arr[8]),
    );
  }

  @protected
  ApiRenderReport dco_decode_api_render_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ApiRenderReport(
      peakDbfsBefore: dco_decode_f_64(arr[0]),
      gainAppliedDb: dco_decode_f_64(arr[1]),
      durationSeconds: dco_decode_f_64(arr[2]),
      sampleRate: dco_decode_u_32(arr[3]),
      integratedLufs: dco_decode_f_64(arr[4]),
      truePeakDbtp: dco_decode_f_64(arr[5]),
      lraLu: dco_decode_f_64(arr[6]),
      sourceIntegratedLufs: dco_decode_f_64(arr[7]),
      masteringApplied: dco_decode_bool(arr[8]),
      masteringGainDb: dco_decode_f_64(arr[9]),
    );
  }

  @protected
  ApiTrack dco_decode_api_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ApiTrack(
      index: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      gainDb: dco_decode_f_64(arr[2]),
      pan: dco_decode_f_64(arr[3]),
      polarityInvert: dco_decode_bool(arr[4]),
      muted: dco_decode_bool(arr[5]),
      solo: dco_decode_bool(arr[6]),
      inMix: dco_decode_bool(arr[7]),
      eq: dco_decode_api_track_eq(arr[8]),
    );
  }

  @protected
  ApiTrackEq dco_decode_api_track_eq(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ApiTrackEq(
      hpfEnabled: dco_decode_bool(arr[0]),
      hpfFreq: dco_decode_f_64(arr[1]),
      hpfSlope: dco_decode_api_hpf_slope(arr[2]),
      low: dco_decode_api_eq_band(arr[3]),
      mid: dco_decode_api_eq_band(arr[4]),
      high: dco_decode_api_eq_band(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ApiMaster dco_decode_box_autoadd_api_master(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_master(raw);
  }

  @protected
  ApiMixStats dco_decode_box_autoadd_api_mix_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_mix_stats(raw);
  }

  @protected
  ApiReferenceProfile dco_decode_box_autoadd_api_reference_profile(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_reference_profile(raw);
  }

  @protected
  ApiRenderReport dco_decode_box_autoadd_api_render_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_render_report(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<ApiChannelWaveform> dco_decode_list_api_channel_waveform(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_channel_waveform).toList();
  }

  @protected
  List<ApiMasteringReference> dco_decode_list_api_mastering_reference(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_api_mastering_reference)
        .toList();
  }

  @protected
  List<ApiReferenceProfile> dco_decode_list_api_reference_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_api_reference_profile)
        .toList();
  }

  @protected
  List<ApiTrack> dco_decode_list_api_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_track).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MixStatsEvent dco_decode_mix_stats_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MixStatsEvent(
      progress: dco_decode_f_32(arr[0]),
      stats: dco_decode_opt_box_autoadd_api_mix_stats(arr[1]),
    );
  }

  @protected
  ApiMixStats? dco_decode_opt_box_autoadd_api_mix_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_api_mix_stats(raw);
  }

  @protected
  ApiReferenceProfile? dco_decode_opt_box_autoadd_api_reference_profile(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_api_reference_profile(raw);
  }

  @protected
  ApiRenderReport? dco_decode_opt_box_autoadd_api_render_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_api_render_report(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  RecordingInfo dco_decode_recording_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RecordingInfo(
      path: dco_decode_String(arr[0]),
      sampleRate: dco_decode_u_32(arr[1]),
      channels: dco_decode_u_16(arr[2]),
      bitsPerSample: dco_decode_u_16(arr[3]),
      numFrames: dco_decode_u_64(arr[4]),
      durationSeconds: dco_decode_f_64(arr[5]),
      tracks: dco_decode_list_api_track(arr[6]),
      master: dco_decode_api_master(arr[7]),
    );
  }

  @protected
  ReferenceEvent dco_decode_reference_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReferenceEvent(
      progress: dco_decode_f_32(arr[0]),
      profile: dco_decode_opt_box_autoadd_api_reference_profile(arr[1]),
    );
  }

  @protected
  RenderEvent dco_decode_render_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RenderEvent(
      progress: dco_decode_f_32(arr[0]),
      report: dco_decode_opt_box_autoadd_api_render_report(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<MixStatsEvent> sse_decode_StreamSink_mix_stats_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ReferenceEvent> sse_decode_StreamSink_reference_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<RenderEvent> sse_decode_StreamSink_render_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiAnalysis sse_decode_api_analysis(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_waveforms = sse_decode_list_api_channel_waveform(deserializer);
    var var_bpm = sse_decode_opt_box_autoadd_f_64(deserializer);
    return ApiAnalysis(waveforms: var_waveforms, bpm: var_bpm);
  }

  @protected
  ApiChannelWaveform sse_decode_api_channel_waveform(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_min = sse_decode_list_prim_f_32_strict(deserializer);
    var var_max = sse_decode_list_prim_f_32_strict(deserializer);
    var var_peakDbfs = sse_decode_f_32(deserializer);
    return ApiChannelWaveform(
      min: var_min,
      max: var_max,
      peakDbfs: var_peakDbfs,
    );
  }

  @protected
  ApiEqBand sse_decode_api_eq_band(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_freq = sse_decode_f_64(deserializer);
    var var_gainDb = sse_decode_f_64(deserializer);
    var var_q = sse_decode_f_64(deserializer);
    return ApiEqBand(
      enabled: var_enabled,
      freq: var_freq,
      gainDb: var_gainDb,
      q: var_q,
    );
  }

  @protected
  ApiFormat sse_decode_api_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApiFormat.values[inner];
  }

  @protected
  ApiHpfSlope sse_decode_api_hpf_slope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApiHpfSlope.values[inner];
  }

  @protected
  ApiLoudness sse_decode_api_loudness(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_api_loudness_mode(deserializer);
    var var_value = sse_decode_f_64(deserializer);
    return ApiLoudness(mode: var_mode, value: var_value);
  }

  @protected
  ApiLoudnessMode sse_decode_api_loudness_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApiLoudnessMode.values[inner];
  }

  @protected
  ApiMaster sse_decode_api_master(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loudness = sse_decode_api_loudness(deserializer);
    var var_format = sse_decode_api_format(deserializer);
    var var_limiterEnabled = sse_decode_bool(deserializer);
    var var_ceilingDbtp = sse_decode_f_64(deserializer);
    var var_dither = sse_decode_bool(deserializer);
    var var_trimStartFrame = sse_decode_u_64(deserializer);
    var var_trimEndFrame = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_fadeInMs = sse_decode_f_64(deserializer);
    var var_fadeOutMs = sse_decode_f_64(deserializer);
    var var_masteringEnabled = sse_decode_bool(deserializer);
    var var_masteringReferences = sse_decode_list_api_mastering_reference(
      deserializer,
    );
    return ApiMaster(
      loudness: var_loudness,
      format: var_format,
      limiterEnabled: var_limiterEnabled,
      ceilingDbtp: var_ceilingDbtp,
      dither: var_dither,
      trimStartFrame: var_trimStartFrame,
      trimEndFrame: var_trimEndFrame,
      fadeInMs: var_fadeInMs,
      fadeOutMs: var_fadeOutMs,
      masteringEnabled: var_masteringEnabled,
      masteringReferences: var_masteringReferences,
    );
  }

  @protected
  ApiMasteringReference sse_decode_api_mastering_reference(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return ApiMasteringReference(path: var_path, name: var_name);
  }

  @protected
  ApiMixStats sse_decode_api_mix_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_midRms = sse_decode_f_64(deserializer);
    var var_sideRms = sse_decode_f_64(deserializer);
    var var_midSpectrum = sse_decode_list_prim_f_64_strict(deserializer);
    var var_sideSpectrum = sse_decode_list_prim_f_64_strict(deserializer);
    var var_midPower = sse_decode_list_prim_f_64_strict(deserializer);
    var var_sidePower = sse_decode_list_prim_f_64_strict(deserializer);
    return ApiMixStats(
      sampleRate: var_sampleRate,
      durationSeconds: var_durationSeconds,
      midRms: var_midRms,
      sideRms: var_sideRms,
      midSpectrum: var_midSpectrum,
      sideSpectrum: var_sideSpectrum,
      midPower: var_midPower,
      sidePower: var_sidePower,
    );
  }

  @protected
  ApiPlayerState sse_decode_api_player_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playing = sse_decode_bool(deserializer);
    var var_positionFrames = sse_decode_u_64(deserializer);
    var var_peakL = sse_decode_f_32(deserializer);
    var var_peakR = sse_decode_f_32(deserializer);
    var var_lufsMomentary = sse_decode_f_32(deserializer);
    var var_lufsIntegrated = sse_decode_f_32(deserializer);
    var var_truePeak = sse_decode_f_32(deserializer);
    var var_correlation = sse_decode_f_32(deserializer);
    return ApiPlayerState(
      playing: var_playing,
      positionFrames: var_positionFrames,
      peakL: var_peakL,
      peakR: var_peakR,
      lufsMomentary: var_lufsMomentary,
      lufsIntegrated: var_lufsIntegrated,
      truePeak: var_truePeak,
      correlation: var_correlation,
    );
  }

  @protected
  ApiProbe sse_decode_api_probe(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_channels = sse_decode_u_16(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_bitsPerSample = sse_decode_u_16(deserializer);
    var var_numFrames = sse_decode_u_64(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_ixmlTrackCount = sse_decode_u_32(deserializer);
    return ApiProbe(
      channels: var_channels,
      sampleRate: var_sampleRate,
      bitsPerSample: var_bitsPerSample,
      numFrames: var_numFrames,
      durationSeconds: var_durationSeconds,
      ixmlTrackCount: var_ixmlTrackCount,
    );
  }

  @protected
  ApiReferenceProfile sse_decode_api_reference_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_32(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_fftSize = sse_decode_u_32(deserializer);
    var var_pieceSeconds = sse_decode_f_64(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_midRms = sse_decode_f_64(deserializer);
    var var_sideRms = sse_decode_f_64(deserializer);
    var var_midSpectrum = sse_decode_list_prim_f_32_strict(deserializer);
    var var_sideSpectrum = sse_decode_list_prim_f_32_strict(deserializer);
    return ApiReferenceProfile(
      version: var_version,
      sampleRate: var_sampleRate,
      fftSize: var_fftSize,
      pieceSeconds: var_pieceSeconds,
      durationSeconds: var_durationSeconds,
      midRms: var_midRms,
      sideRms: var_sideRms,
      midSpectrum: var_midSpectrum,
      sideSpectrum: var_sideSpectrum,
    );
  }

  @protected
  ApiRenderReport sse_decode_api_render_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peakDbfsBefore = sse_decode_f_64(deserializer);
    var var_gainAppliedDb = sse_decode_f_64(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_integratedLufs = sse_decode_f_64(deserializer);
    var var_truePeakDbtp = sse_decode_f_64(deserializer);
    var var_lraLu = sse_decode_f_64(deserializer);
    var var_sourceIntegratedLufs = sse_decode_f_64(deserializer);
    var var_masteringApplied = sse_decode_bool(deserializer);
    var var_masteringGainDb = sse_decode_f_64(deserializer);
    return ApiRenderReport(
      peakDbfsBefore: var_peakDbfsBefore,
      gainAppliedDb: var_gainAppliedDb,
      durationSeconds: var_durationSeconds,
      sampleRate: var_sampleRate,
      integratedLufs: var_integratedLufs,
      truePeakDbtp: var_truePeakDbtp,
      lraLu: var_lraLu,
      sourceIntegratedLufs: var_sourceIntegratedLufs,
      masteringApplied: var_masteringApplied,
      masteringGainDb: var_masteringGainDb,
    );
  }

  @protected
  ApiTrack sse_decode_api_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_gainDb = sse_decode_f_64(deserializer);
    var var_pan = sse_decode_f_64(deserializer);
    var var_polarityInvert = sse_decode_bool(deserializer);
    var var_muted = sse_decode_bool(deserializer);
    var var_solo = sse_decode_bool(deserializer);
    var var_inMix = sse_decode_bool(deserializer);
    var var_eq = sse_decode_api_track_eq(deserializer);
    return ApiTrack(
      index: var_index,
      name: var_name,
      gainDb: var_gainDb,
      pan: var_pan,
      polarityInvert: var_polarityInvert,
      muted: var_muted,
      solo: var_solo,
      inMix: var_inMix,
      eq: var_eq,
    );
  }

  @protected
  ApiTrackEq sse_decode_api_track_eq(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hpfEnabled = sse_decode_bool(deserializer);
    var var_hpfFreq = sse_decode_f_64(deserializer);
    var var_hpfSlope = sse_decode_api_hpf_slope(deserializer);
    var var_low = sse_decode_api_eq_band(deserializer);
    var var_mid = sse_decode_api_eq_band(deserializer);
    var var_high = sse_decode_api_eq_band(deserializer);
    return ApiTrackEq(
      hpfEnabled: var_hpfEnabled,
      hpfFreq: var_hpfFreq,
      hpfSlope: var_hpfSlope,
      low: var_low,
      mid: var_mid,
      high: var_high,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ApiMaster sse_decode_box_autoadd_api_master(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_master(deserializer));
  }

  @protected
  ApiMixStats sse_decode_box_autoadd_api_mix_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_mix_stats(deserializer));
  }

  @protected
  ApiReferenceProfile sse_decode_box_autoadd_api_reference_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_reference_profile(deserializer));
  }

  @protected
  ApiRenderReport sse_decode_box_autoadd_api_render_report(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_render_report(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<ApiChannelWaveform> sse_decode_list_api_channel_waveform(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiChannelWaveform>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_channel_waveform(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiMasteringReference> sse_decode_list_api_mastering_reference(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiMasteringReference>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_mastering_reference(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiReferenceProfile> sse_decode_list_api_reference_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiReferenceProfile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_reference_profile(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiTrack> sse_decode_list_api_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiTrack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_track(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MixStatsEvent sse_decode_mix_stats_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_f_32(deserializer);
    var var_stats = sse_decode_opt_box_autoadd_api_mix_stats(deserializer);
    return MixStatsEvent(progress: var_progress, stats: var_stats);
  }

  @protected
  ApiMixStats? sse_decode_opt_box_autoadd_api_mix_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_api_mix_stats(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ApiReferenceProfile? sse_decode_opt_box_autoadd_api_reference_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_api_reference_profile(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ApiRenderReport? sse_decode_opt_box_autoadd_api_render_report(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_api_render_report(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RecordingInfo sse_decode_recording_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_channels = sse_decode_u_16(deserializer);
    var var_bitsPerSample = sse_decode_u_16(deserializer);
    var var_numFrames = sse_decode_u_64(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_tracks = sse_decode_list_api_track(deserializer);
    var var_master = sse_decode_api_master(deserializer);
    return RecordingInfo(
      path: var_path,
      sampleRate: var_sampleRate,
      channels: var_channels,
      bitsPerSample: var_bitsPerSample,
      numFrames: var_numFrames,
      durationSeconds: var_durationSeconds,
      tracks: var_tracks,
      master: var_master,
    );
  }

  @protected
  ReferenceEvent sse_decode_reference_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_f_32(deserializer);
    var var_profile = sse_decode_opt_box_autoadd_api_reference_profile(
      deserializer,
    );
    return ReferenceEvent(progress: var_progress, profile: var_profile);
  }

  @protected
  RenderEvent sse_decode_render_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_f_32(deserializer);
    var var_report = sse_decode_opt_box_autoadd_api_render_report(deserializer);
    return RenderEvent(progress: var_progress, report: var_report);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_mix_stats_event_Sse(
    RustStreamSink<MixStatsEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_mix_stats_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_reference_event_Sse(
    RustStreamSink<ReferenceEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_reference_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_render_event_Sse(
    RustStreamSink<RenderEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_analysis(ApiAnalysis self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_api_channel_waveform(self.waveforms, serializer);
    sse_encode_opt_box_autoadd_f_64(self.bpm, serializer);
  }

  @protected
  void sse_encode_api_channel_waveform(
    ApiChannelWaveform self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_32_strict(self.min, serializer);
    sse_encode_list_prim_f_32_strict(self.max, serializer);
    sse_encode_f_32(self.peakDbfs, serializer);
  }

  @protected
  void sse_encode_api_eq_band(ApiEqBand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_64(self.freq, serializer);
    sse_encode_f_64(self.gainDb, serializer);
    sse_encode_f_64(self.q, serializer);
  }

  @protected
  void sse_encode_api_format(ApiFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_hpf_slope(ApiHpfSlope self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_loudness(ApiLoudness self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_loudness_mode(self.mode, serializer);
    sse_encode_f_64(self.value, serializer);
  }

  @protected
  void sse_encode_api_loudness_mode(
    ApiLoudnessMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_master(ApiMaster self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_loudness(self.loudness, serializer);
    sse_encode_api_format(self.format, serializer);
    sse_encode_bool(self.limiterEnabled, serializer);
    sse_encode_f_64(self.ceilingDbtp, serializer);
    sse_encode_bool(self.dither, serializer);
    sse_encode_u_64(self.trimStartFrame, serializer);
    sse_encode_opt_box_autoadd_u_64(self.trimEndFrame, serializer);
    sse_encode_f_64(self.fadeInMs, serializer);
    sse_encode_f_64(self.fadeOutMs, serializer);
    sse_encode_bool(self.masteringEnabled, serializer);
    sse_encode_list_api_mastering_reference(
      self.masteringReferences,
      serializer,
    );
  }

  @protected
  void sse_encode_api_mastering_reference(
    ApiMasteringReference self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_api_mix_stats(ApiMixStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_f_64(self.midRms, serializer);
    sse_encode_f_64(self.sideRms, serializer);
    sse_encode_list_prim_f_64_strict(self.midSpectrum, serializer);
    sse_encode_list_prim_f_64_strict(self.sideSpectrum, serializer);
    sse_encode_list_prim_f_64_strict(self.midPower, serializer);
    sse_encode_list_prim_f_64_strict(self.sidePower, serializer);
  }

  @protected
  void sse_encode_api_player_state(
    ApiPlayerState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.playing, serializer);
    sse_encode_u_64(self.positionFrames, serializer);
    sse_encode_f_32(self.peakL, serializer);
    sse_encode_f_32(self.peakR, serializer);
    sse_encode_f_32(self.lufsMomentary, serializer);
    sse_encode_f_32(self.lufsIntegrated, serializer);
    sse_encode_f_32(self.truePeak, serializer);
    sse_encode_f_32(self.correlation, serializer);
  }

  @protected
  void sse_encode_api_probe(ApiProbe self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.channels, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_16(self.bitsPerSample, serializer);
    sse_encode_u_64(self.numFrames, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_u_32(self.ixmlTrackCount, serializer);
  }

  @protected
  void sse_encode_api_reference_profile(
    ApiReferenceProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.version, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_32(self.fftSize, serializer);
    sse_encode_f_64(self.pieceSeconds, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_f_64(self.midRms, serializer);
    sse_encode_f_64(self.sideRms, serializer);
    sse_encode_list_prim_f_32_strict(self.midSpectrum, serializer);
    sse_encode_list_prim_f_32_strict(self.sideSpectrum, serializer);
  }

  @protected
  void sse_encode_api_render_report(
    ApiRenderReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.peakDbfsBefore, serializer);
    sse_encode_f_64(self.gainAppliedDb, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_f_64(self.integratedLufs, serializer);
    sse_encode_f_64(self.truePeakDbtp, serializer);
    sse_encode_f_64(self.lraLu, serializer);
    sse_encode_f_64(self.sourceIntegratedLufs, serializer);
    sse_encode_bool(self.masteringApplied, serializer);
    sse_encode_f_64(self.masteringGainDb, serializer);
  }

  @protected
  void sse_encode_api_track(ApiTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_f_64(self.gainDb, serializer);
    sse_encode_f_64(self.pan, serializer);
    sse_encode_bool(self.polarityInvert, serializer);
    sse_encode_bool(self.muted, serializer);
    sse_encode_bool(self.solo, serializer);
    sse_encode_bool(self.inMix, serializer);
    sse_encode_api_track_eq(self.eq, serializer);
  }

  @protected
  void sse_encode_api_track_eq(ApiTrackEq self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.hpfEnabled, serializer);
    sse_encode_f_64(self.hpfFreq, serializer);
    sse_encode_api_hpf_slope(self.hpfSlope, serializer);
    sse_encode_api_eq_band(self.low, serializer);
    sse_encode_api_eq_band(self.mid, serializer);
    sse_encode_api_eq_band(self.high, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_api_master(
    ApiMaster self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_master(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_api_mix_stats(
    ApiMixStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_mix_stats(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_api_reference_profile(
    ApiReferenceProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_reference_profile(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_api_render_report(
    ApiRenderReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_render_report(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_api_channel_waveform(
    List<ApiChannelWaveform> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_channel_waveform(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_mastering_reference(
    List<ApiMasteringReference> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_mastering_reference(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_reference_profile(
    List<ApiReferenceProfile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_reference_profile(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_track(
    List<ApiTrack> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_track(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mix_stats_event(
    MixStatsEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.progress, serializer);
    sse_encode_opt_box_autoadd_api_mix_stats(self.stats, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_api_mix_stats(
    ApiMixStats? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_api_mix_stats(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_api_reference_profile(
    ApiReferenceProfile? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_api_reference_profile(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_api_render_report(
    ApiRenderReport? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_api_render_report(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_recording_info(RecordingInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_16(self.channels, serializer);
    sse_encode_u_16(self.bitsPerSample, serializer);
    sse_encode_u_64(self.numFrames, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_list_api_track(self.tracks, serializer);
    sse_encode_api_master(self.master, serializer);
  }

  @protected
  void sse_encode_reference_event(
    ReferenceEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.progress, serializer);
    sse_encode_opt_box_autoadd_api_reference_profile(self.profile, serializer);
  }

  @protected
  void sse_encode_render_event(RenderEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.progress, serializer);
    sse_encode_opt_box_autoadd_api_render_report(self.report, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
