// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_engine_track`, `player_slot`, `to_engine_settings`, `to_engine_track`

/// Open a multichannel WAV/RF64, parse iXML track metadata and merge the
/// session at `session_path` (falling back once to a legacy sibling file
/// next to the WAV, from before sessions moved into the app container).
Future<RecordingInfo> loadRecording({
  required String path,
  required String sessionPath,
}) => RustLib.instance.api.crateApiMixerLoadRecording(
  path: path,
  sessionPath: sessionPath,
);

/// Persist the current mix to `session_path` (an app-container location
/// chosen by the UI layer; parent directories are created as needed).
Future<void> saveSession({
  required String sessionPath,
  required List<ApiTrack> tracks,
  double? peakDbfs,
  required ApiFormat format,
}) => RustLib.instance.api.crateApiMixerSaveSession(
  sessionPath: sessionPath,
  tracks: tracks,
  peakDbfs: peakDbfs,
  format: format,
);

/// Render the stereo mixdown. Streams `RenderEvent`s to Dart: progress in
/// 0.0..1.0 while rendering, then a final event with the report attached.
Stream<RenderEvent> renderMix({
  required String wavPath,
  required String outPath,
  required List<ApiTrack> tracks,
  double? peakDbfs,
  required ApiFormat format,
}) => RustLib.instance.api.crateApiMixerRenderMix(
  wavPath: wavPath,
  outPath: outPath,
  tracks: tracks,
  peakDbfs: peakDbfs,
  format: format,
);

/// Streamed min/max envelope of every channel, `buckets` values per channel.
Future<List<ApiChannelWaveform>> analyzeWaveforms({
  required String path,
  required BigInt buckets,
}) => RustLib.instance.api.crateApiMixerAnalyzeWaveforms(
  path: path,
  buckets: buckets,
);

/// Start (or restart) live playback of the mix at `start_frame`.
Future<void> playerStart({
  required String path,
  required List<ApiTrack> tracks,
  required BigInt startFrame,
}) => RustLib.instance.api.crateApiMixerPlayerStart(
  path: path,
  tracks: tracks,
  startFrame: startFrame,
);

Future<void> playerStop() => RustLib.instance.api.crateApiMixerPlayerStop();

Future<void> playerSeek({required BigInt frame}) =>
    RustLib.instance.api.crateApiMixerPlayerSeek(frame: frame);

/// Push updated mix parameters to the running player (audible in ~0.2 s).
Future<void> playerUpdateTracks({required List<ApiTrack> tracks}) =>
    RustLib.instance.api.crateApiMixerPlayerUpdateTracks(tracks: tracks);

/// Poll playback position and meters (call at UI frame rate).
ApiPlayerState playerState() => RustLib.instance.api.crateApiMixerPlayerState();

class ApiChannelWaveform {
  final Float32List min;
  final Float32List max;
  final double peakDbfs;

  const ApiChannelWaveform({
    required this.min,
    required this.max,
    required this.peakDbfs,
  });

  @override
  int get hashCode => min.hashCode ^ max.hashCode ^ peakDbfs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiChannelWaveform &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max &&
          peakDbfs == other.peakDbfs;
}

enum ApiFormat { wav16, wav24, wav32Float }

class ApiPlayerState {
  final bool playing;
  final BigInt positionFrames;
  final double peakL;
  final double peakR;
  final double lufsMomentary;
  final double correlation;

  const ApiPlayerState({
    required this.playing,
    required this.positionFrames,
    required this.peakL,
    required this.peakR,
    required this.lufsMomentary,
    required this.correlation,
  });

  @override
  int get hashCode =>
      playing.hashCode ^
      positionFrames.hashCode ^
      peakL.hashCode ^
      peakR.hashCode ^
      lufsMomentary.hashCode ^
      correlation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPlayerState &&
          runtimeType == other.runtimeType &&
          playing == other.playing &&
          positionFrames == other.positionFrames &&
          peakL == other.peakL &&
          peakR == other.peakR &&
          lufsMomentary == other.lufsMomentary &&
          correlation == other.correlation;
}

class ApiRenderReport {
  final double peakDbfsBefore;
  final double gainAppliedDb;
  final double durationSeconds;
  final int sampleRate;

  const ApiRenderReport({
    required this.peakDbfsBefore,
    required this.gainAppliedDb,
    required this.durationSeconds,
    required this.sampleRate,
  });

  @override
  int get hashCode =>
      peakDbfsBefore.hashCode ^
      gainAppliedDb.hashCode ^
      durationSeconds.hashCode ^
      sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRenderReport &&
          runtimeType == other.runtimeType &&
          peakDbfsBefore == other.peakDbfsBefore &&
          gainAppliedDb == other.gainAppliedDb &&
          durationSeconds == other.durationSeconds &&
          sampleRate == other.sampleRate;
}

class ApiTrack {
  final int index;
  final String name;
  final double gainDb;
  final double pan;
  final bool polarityInvert;
  final bool muted;
  final bool solo;
  final bool inMix;

  const ApiTrack({
    required this.index,
    required this.name,
    required this.gainDb,
    required this.pan,
    required this.polarityInvert,
    required this.muted,
    required this.solo,
    required this.inMix,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      name.hashCode ^
      gainDb.hashCode ^
      pan.hashCode ^
      polarityInvert.hashCode ^
      muted.hashCode ^
      solo.hashCode ^
      inMix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTrack &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          gainDb == other.gainDb &&
          pan == other.pan &&
          polarityInvert == other.polarityInvert &&
          muted == other.muted &&
          solo == other.solo &&
          inMix == other.inMix;
}

class RecordingInfo {
  final String path;
  final int sampleRate;
  final int channels;
  final int bitsPerSample;
  final BigInt numFrames;
  final double durationSeconds;
  final List<ApiTrack> tracks;

  const RecordingInfo({
    required this.path,
    required this.sampleRate,
    required this.channels,
    required this.bitsPerSample,
    required this.numFrames,
    required this.durationSeconds,
    required this.tracks,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bitsPerSample.hashCode ^
      numFrames.hashCode ^
      durationSeconds.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordingInfo &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitsPerSample == other.bitsPerSample &&
          numFrames == other.numFrames &&
          durationSeconds == other.durationSeconds &&
          tracks == other.tracks;
}

/// One event of the render stream: progress ticks while rendering, and the
/// final event (progress == 1.0) carries the report.
class RenderEvent {
  final double progress;
  final ApiRenderReport? report;

  const RenderEvent({required this.progress, this.report});

  @override
  int get hashCode => progress.hashCode ^ report.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderEvent &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          report == other.report;
}
