// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_engine_band`, `from_engine_eq`, `from_engine_settings`, `from_engine_track`, `player_slot`, `to_engine_band`, `to_engine_eq`, `to_engine_settings`, `to_engine_track`, `to_master_params`

/// Open a multichannel WAV/RF64, parse iXML track metadata and merge the
/// session at `session_path` (falling back once to a legacy sibling file
/// next to the WAV, from before sessions moved into the app container).
Future<RecordingInfo> loadRecording({
  required String path,
  required String sessionPath,
}) => RustLib.instance.api.crateApiMixerLoadRecording(
  path: path,
  sessionPath: sessionPath,
);

/// Persist the current mix to `session_path` (an app-container location
/// chosen by the UI layer; parent directories are created as needed).
Future<void> saveSession({
  required String sessionPath,
  required List<ApiTrack> tracks,
  required ApiMaster master,
}) => RustLib.instance.api.crateApiMixerSaveSession(
  sessionPath: sessionPath,
  tracks: tracks,
  master: master,
);

/// Render the stereo mixdown. Streams `RenderEvent`s to Dart: progress in
/// 0.0..1.0 while rendering, then a final event with the report attached.
Stream<RenderEvent> renderMix({
  required String wavPath,
  required String outPath,
  required List<ApiTrack> tracks,
  required ApiMaster master,
}) => RustLib.instance.api.crateApiMixerRenderMix(
  wavPath: wavPath,
  outPath: outPath,
  tracks: tracks,
  master: master,
);

/// Streamed min/max envelope of every channel, `buckets` values per channel.
Future<List<ApiChannelWaveform>> analyzeWaveforms({
  required String path,
  required BigInt buckets,
}) => RustLib.instance.api.crateApiMixerAnalyzeWaveforms(
  path: path,
  buckets: buckets,
);

/// Start (or restart) live playback of the mix at `start_frame`.
Future<void> playerStart({
  required String path,
  required List<ApiTrack> tracks,
  required ApiMaster master,
  required BigInt startFrame,
}) => RustLib.instance.api.crateApiMixerPlayerStart(
  path: path,
  tracks: tracks,
  master: master,
  startFrame: startFrame,
);

Future<void> playerStop() => RustLib.instance.api.crateApiMixerPlayerStop();

Future<void> playerSeek({required BigInt frame}) =>
    RustLib.instance.api.crateApiMixerPlayerSeek(frame: frame);

/// Push updated mix/master parameters to the running player (~0.2 s).
Future<void> playerUpdateParams({
  required List<ApiTrack> tracks,
  required ApiMaster master,
}) => RustLib.instance.api.crateApiMixerPlayerUpdateParams(
  tracks: tracks,
  master: master,
);

/// Poll playback position and meters (call at UI frame rate).
ApiPlayerState playerState() => RustLib.instance.api.crateApiMixerPlayerState();

class ApiChannelWaveform {
  final Float32List min;
  final Float32List max;
  final double peakDbfs;

  const ApiChannelWaveform({
    required this.min,
    required this.max,
    required this.peakDbfs,
  });

  @override
  int get hashCode => min.hashCode ^ max.hashCode ^ peakDbfs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiChannelWaveform &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max &&
          peakDbfs == other.peakDbfs;
}

class ApiEqBand {
  final bool enabled;
  final double freq;
  final double gainDb;
  final double q;

  const ApiEqBand({
    required this.enabled,
    required this.freq,
    required this.gainDb,
    required this.q,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ freq.hashCode ^ gainDb.hashCode ^ q.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiEqBand &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          freq == other.freq &&
          gainDb == other.gainDb &&
          q == other.q;
}

enum ApiFormat { wav16, wav24, wav32Float }

enum ApiHpfSlope { db12, db24 }

/// Loudness target: `value` is dBFS for `PeakDbfs`, LUFS for
/// `LufsIntegrated`, ignored for `None`. (A plain struct instead of an enum
/// with payload — FRB would need freezed for the latter.)
class ApiLoudness {
  final ApiLoudnessMode mode;
  final double value;

  const ApiLoudness({required this.mode, required this.value});

  @override
  int get hashCode => mode.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiLoudness &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          value == other.value;
}

enum ApiLoudnessMode { none, peakDbfs, lufsIntegrated }

/// Master-bus settings: loudness target, output format, limiter, dither.
class ApiMaster {
  final ApiLoudness loudness;
  final ApiFormat format;
  final bool limiterEnabled;
  final double ceilingDbtp;
  final bool dither;

  const ApiMaster({
    required this.loudness,
    required this.format,
    required this.limiterEnabled,
    required this.ceilingDbtp,
    required this.dither,
  });

  @override
  int get hashCode =>
      loudness.hashCode ^
      format.hashCode ^
      limiterEnabled.hashCode ^
      ceilingDbtp.hashCode ^
      dither.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMaster &&
          runtimeType == other.runtimeType &&
          loudness == other.loudness &&
          format == other.format &&
          limiterEnabled == other.limiterEnabled &&
          ceilingDbtp == other.ceilingDbtp &&
          dither == other.dither;
}

class ApiPlayerState {
  final bool playing;
  final BigInt positionFrames;
  final double peakL;
  final double peakR;
  final double lufsMomentary;

  /// Integrated loudness since start/seek — pre-normalisation preview.
  final double lufsIntegrated;

  /// Running true-peak max since start/seek (linear).
  final double truePeak;
  final double correlation;

  const ApiPlayerState({
    required this.playing,
    required this.positionFrames,
    required this.peakL,
    required this.peakR,
    required this.lufsMomentary,
    required this.lufsIntegrated,
    required this.truePeak,
    required this.correlation,
  });

  @override
  int get hashCode =>
      playing.hashCode ^
      positionFrames.hashCode ^
      peakL.hashCode ^
      peakR.hashCode ^
      lufsMomentary.hashCode ^
      lufsIntegrated.hashCode ^
      truePeak.hashCode ^
      correlation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPlayerState &&
          runtimeType == other.runtimeType &&
          playing == other.playing &&
          positionFrames == other.positionFrames &&
          peakL == other.peakL &&
          peakR == other.peakR &&
          lufsMomentary == other.lufsMomentary &&
          lufsIntegrated == other.lufsIntegrated &&
          truePeak == other.truePeak &&
          correlation == other.correlation;
}

class ApiRenderReport {
  final double peakDbfsBefore;
  final double gainAppliedDb;
  final double durationSeconds;
  final int sampleRate;
  final double integratedLufs;
  final double truePeakDbtp;
  final double lraLu;
  final double sourceIntegratedLufs;

  const ApiRenderReport({
    required this.peakDbfsBefore,
    required this.gainAppliedDb,
    required this.durationSeconds,
    required this.sampleRate,
    required this.integratedLufs,
    required this.truePeakDbtp,
    required this.lraLu,
    required this.sourceIntegratedLufs,
  });

  @override
  int get hashCode =>
      peakDbfsBefore.hashCode ^
      gainAppliedDb.hashCode ^
      durationSeconds.hashCode ^
      sampleRate.hashCode ^
      integratedLufs.hashCode ^
      truePeakDbtp.hashCode ^
      lraLu.hashCode ^
      sourceIntegratedLufs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRenderReport &&
          runtimeType == other.runtimeType &&
          peakDbfsBefore == other.peakDbfsBefore &&
          gainAppliedDb == other.gainAppliedDb &&
          durationSeconds == other.durationSeconds &&
          sampleRate == other.sampleRate &&
          integratedLufs == other.integratedLufs &&
          truePeakDbtp == other.truePeakDbtp &&
          lraLu == other.lraLu &&
          sourceIntegratedLufs == other.sourceIntegratedLufs;
}

class ApiTrack {
  final int index;
  final String name;
  final double gainDb;
  final double pan;
  final bool polarityInvert;
  final bool muted;
  final bool solo;
  final bool inMix;
  final ApiTrackEq eq;

  const ApiTrack({
    required this.index,
    required this.name,
    required this.gainDb,
    required this.pan,
    required this.polarityInvert,
    required this.muted,
    required this.solo,
    required this.inMix,
    required this.eq,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      name.hashCode ^
      gainDb.hashCode ^
      pan.hashCode ^
      polarityInvert.hashCode ^
      muted.hashCode ^
      solo.hashCode ^
      inMix.hashCode ^
      eq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTrack &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          gainDb == other.gainDb &&
          pan == other.pan &&
          polarityInvert == other.polarityInvert &&
          muted == other.muted &&
          solo == other.solo &&
          inMix == other.inMix &&
          eq == other.eq;
}

class ApiTrackEq {
  final bool hpfEnabled;
  final double hpfFreq;
  final ApiHpfSlope hpfSlope;
  final ApiEqBand low;
  final ApiEqBand mid;
  final ApiEqBand high;

  const ApiTrackEq({
    required this.hpfEnabled,
    required this.hpfFreq,
    required this.hpfSlope,
    required this.low,
    required this.mid,
    required this.high,
  });

  @override
  int get hashCode =>
      hpfEnabled.hashCode ^
      hpfFreq.hashCode ^
      hpfSlope.hashCode ^
      low.hashCode ^
      mid.hashCode ^
      high.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTrackEq &&
          runtimeType == other.runtimeType &&
          hpfEnabled == other.hpfEnabled &&
          hpfFreq == other.hpfFreq &&
          hpfSlope == other.hpfSlope &&
          low == other.low &&
          mid == other.mid &&
          high == other.high;
}

class RecordingInfo {
  final String path;
  final int sampleRate;
  final int channels;
  final int bitsPerSample;
  final BigInt numFrames;
  final double durationSeconds;
  final List<ApiTrack> tracks;

  /// Master settings restored from the session (defaults for a fresh take).
  final ApiMaster master;

  const RecordingInfo({
    required this.path,
    required this.sampleRate,
    required this.channels,
    required this.bitsPerSample,
    required this.numFrames,
    required this.durationSeconds,
    required this.tracks,
    required this.master,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bitsPerSample.hashCode ^
      numFrames.hashCode ^
      durationSeconds.hashCode ^
      tracks.hashCode ^
      master.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordingInfo &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitsPerSample == other.bitsPerSample &&
          numFrames == other.numFrames &&
          durationSeconds == other.durationSeconds &&
          tracks == other.tracks &&
          master == other.master;
}

/// One event of the render stream: progress ticks while rendering, and the
/// final event (progress == 1.0) carries the report.
class RenderEvent {
  final double progress;
  final ApiRenderReport? report;

  const RenderEvent({required this.progress, this.report});

  @override
  int get hashCode => progress.hashCode ^ report.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderEvent &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          report == other.report;
}
